name: Repo Naming Convention

# Trigger the workflow 
on:
  # Allow manual triggers
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # Run the naming convention script
    - name: Run Repo Naming Convention Script
      run: |
        chmod +x ./scripts/repo-naming-convention-1.sh
        ./scripts/repo-naming-convention-1.sh
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}  # Use GitHub's default token
        ORG_NAME: RepoNamingConventionDemo  # Replace with your organization name
